PROFILE = {
    "display_name": "Nishanth G",
    "host": "Dr. N.G.P. Institute of Technology",
    "kernel": "Artificial Intelligence & Data Science",
    "ide": "VS Code, IntelliJ IDEA, Jupyter",
    "programming": "Python, Java, JavaScript, C++",
    "frontend": "HTML, CSS, React, TypeScript",
    "real": "English, Tamil",
    "software_hobbies": "AI/ML, Full Stack, Open Source",
    "hardware_hobbies": "PC Building, Gaming",
    "personal_email": "your-email@example.com",
    "work_email": "your-work-email@example.com",
    "linkedin": "nishanth-g",
    "discord": "nishanth6153",
}
